- name: "Install nvm"
  become: false
  shell: >
    curl -o-  https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
  args:
    executable: /bin/bash
    chdir: "$HOME"
    creates: "$HOME/.nvm/nvm.sh"

- name: "Install Node"
  become: false
  shell: >
    . $HOME/.nvm/nvm.sh && nvm install --lts
  args:
    executable: /bin/bash
    chdir: "$HOME"
