- name: "Install nvm"
  become: false
  shell: >
    curl -o-  https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
  args:
    executable: /bin/bash
    chdir: "$HOME"
    creates: "$HOME/.nvm/nvm.sh"

- name: "Install Node"
  become: false
  shell: >
    . $HOME/.nvm/nvm.sh && nvm install --lts
  args:
    executable: /bin/bash
    chdir: "$HOME"

- name: "Enable corepack"
  become: false
  shell: >
    corepack enable

- name: Installs pnpm
  become: false
  command: corepack install --global pnpm@*

- name: Install yarn
  become: false
  command: corepack install --global yarn@stable  

- name: Install ts-node
  become: false
  command: npm install --global ts-node@latest
